# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14d62afde49cca125e1600ef152dca3603a9ad1aa2504336171bdf6e5540344b73ed8219595ac5e44b0fddfb9f07ebed1fcf4bf39d0df85f0bb6de277b963c83

test:
  secret_key_base: 077e802b0f2a0f58ec8915ab07b80a27b716bba7afc37c15eac32084827c18d91af16f4b475a9bf1d42b1ea6290eb2ec0076e9d54ae2192a82ea44497520393f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
